name: Build Android APK

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mesfactures-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
        cache: 'npm'
        cache-dependency-path: mesfactures-app/package-lock.json

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: npm run build

    # Optionnel: Installer bcryptjs pour l'environnement mobile
    - name: Install mobile-specific dependencies
      run: npm install bcryptjs @types/bcryptjs --no-save

    - name: Capacitor sync
      run: npx cap sync android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Android APK
      run: cd android && ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mesfactures-app-debug
        path: mesfactures-app/android/app/build/outputs/apk/debug/app-debug.apk

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: mesfactures-app/android/app/build/outputs/apk/debug/app-debug.apk
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}